name: "React CI/CD build"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  react:
   runs-on: ubuntu-latest

   steps: 
     - name: Checkout code
       uses: actions/checkout@v3
    
     - name: Install dependencies
       run: cd frontend && npm install

     - name: Build up
       run: cd frontend && npm run build

    #  - name: Test app
    #    run: cd frontend && npm test